MAP_BASIC = {
    0: [
        {'row': 6, 'col': 0, 'piece_type': 'Pawn'},
        {'row': 6, 'col': 1, 'piece_type': 'Pawn'},
        {'row': 6, 'col': 2, 'piece_type': 'Pawn'},
        {'row': 6, 'col': 3, 'piece_type': 'Pawn'},
        {'row': 6, 'col': 4, 'piece_type': 'Pawn'},
        {'row': 6, 'col': 5, 'piece_type': 'Pawn'},
        {'row': 6, 'col': 6, 'piece_type': 'Pawn'},
        {'row': 6, 'col': 7, 'piece_type': 'Pawn'},
        {'row': 7, 'col': 0, 'piece_type': 'Rook'},
        {'row': 7, 'col': 1, 'piece_type': 'Knight'},
        {'row': 7, 'col': 2, 'piece_type': 'Bishop'},
        {'row': 7, 'col': 3, 'piece_type': 'Queen'},
        {'row': 7, 'col': 4, 'piece_type': 'King'},
        {'row': 7, 'col': 5, 'piece_type': 'Bishop'},
        {'row': 7, 'col': 6, 'piece_type': 'Knight'},
        {'row': 7, 'col': 7, 'piece_type': 'Rook'},
        ],
    1: [
        {'row': 1, 'col': 0, 'piece_type': 'Pawn'},
        {'row': 1, 'col': 1, 'piece_type': 'Pawn'},
        {'row': 1, 'col': 2, 'piece_type': 'Pawn'},
        {'row': 1, 'col': 3, 'piece_type': 'Pawn'},
        {'row': 1, 'col': 4, 'piece_type': 'Pawn'},
        {'row': 1, 'col': 5, 'piece_type': 'Pawn'},
        {'row': 1, 'col': 6, 'piece_type': 'Pawn'},
        {'row': 1, 'col': 7, 'piece_type': 'Pawn'},
        {'row': 0, 'col': 0, 'piece_type': 'Rook'},
        {'row': 0, 'col': 1, 'piece_type': 'Knight'},
        {'row': 0, 'col': 2, 'piece_type': 'Bishop'},
        {'row': 0, 'col': 3, 'piece_type': 'Queen'},
        {'row': 0, 'col': 4, 'piece_type': 'King'},
        {'row': 0, 'col': 5, 'piece_type': 'Bishop'},
        {'row': 0, 'col': 6, 'piece_type': 'Knight'},
        {'row': 0, 'col': 7, 'piece_type': 'Rook'},
    ],
}